#ifndef PIXMAPS_H
#define PIXMAPS_H

static const char *print_xpm[]={
"32 32 12 1",
"a c #ffffff",
"h c #ffff00",
"c c #ffffff",
"f c #dcdcdc",
"b c #c0c0c0",
"j c #a0a0a4",
"e c #808080",
"g c #808000",
"d c #585858",
"i c #00ff00",
"# c #000000",
". c None",
"................................",
"................................",
"...........###..................",
"..........#abb###...............",
".........#aabbbbb###............",
".........#ddaaabbbbb###.........",
"........#ddddddaaabbbbb###......",
".......#deffddddddaaabbbbb###...",
"......#deaaabbbddddddaaabbbbb###",
".....#deaaaaaaabbbddddddaaabbbb#",
"....#deaaabbbaaaa#ddedddfggaaad#",
"...#deaaaaaaaaaa#ddeeeeafgggfdd#",
"..#deaaabbbaaaa#ddeeeeabbbbgfdd#",
".#deeefaaaaaaa#ddeeeeabbhhbbadd#",
"#aabbbeeefaaa#ddeeeeabbbbbbaddd#",
"#bbaaabbbeee#ddeeeeabbiibbadddd#",
"#bbbbbaaabbbeeeeeeabbbbbbaddddd#",
"#bjbbbbbbaaabbbbeabbbbbbadddddd#",
"#bjjjjbbbbbbaaaeabbbbbbaddddddd#",
"#bjaaajjjbbbbbbaaabbbbadddddddd#",
"#bbbbbaaajjjbbbbbbaaaaddddddddd#",
"#bjbbbbbbaaajjjbbbbbbddddddddd#.",
"#bjjjjbbbbbbaaajjjbbbdddddddd#..",
"#bjaaajjjbbbbbbjaajjbddddddd#...",
"#bbbbbaaajjjbbbjbbaabdddddd#....",
"###bbbbbbaaajjjjbbbbbddddd#.....",
"...###bbbbbbaaajbbbbbdddd#......",
"......###bbbbbbjbbbbbddd#.......",
".........###bbbbbbbbbdd#........",
"............###bbbbbbd#.........",
"...............###bbb#..........",
"..................###..........."};


static const char *zoom_xpm[]={
"32 32 8 1",
"# c #000000",
"b c #c0c0c0",
"a c #ffffff",
"e c #585858",
"d c #a0a0a4",
"c c #0000ff",
"f c #00ffff",
". c None",
"..######################........",
".#a#baaaaaaaaaaaaaaaaaa#........",
"#aa#baaaaaaaaaaaaaccaca#........",
"####baaaaaaaaaaaaaaaaca####.....",
"#bbbbaaaaaaaaaaaacccaaa#da#.....",
"#aaaaaaaaaaaaaaaacccaca#da#.....",
"#aaaaaaaaaaaaaaaaaccaca#da#.....",
"#aaaaaaaaaabe###ebaaaaa#da#.....",
"#aaaaaaaaa#########aaaa#da#.....",
"#aaaaaaaa###dbbbb###aaa#da#.....",
"#aaaaaaa###aaaaffb###aa#da#.....",
"#aaaaaab##aaccaaafb##ba#da#.....",
"#aaaaaae#daaccaccaad#ea#da#.....",
"#aaaaaa##aaaaaaccaab##a#da#.....",
"#aaaaaa##aacccaaaaab##a#da#.....",
"#aaaaaa##aaccccaccab##a#da#.....",
"#aaaaaae#daccccaccad#ea#da#.....",
"#aaaaaab##aacccaaaa##da#da#.....",
"#aaccacd###aaaaaaa###da#da#.....",
"#aaaaacad###daaad#####a#da#.....",
"#acccaaaad##########da##da#.....",
"#acccacaaadde###edd#eda#da#.....",
"#aaccacaaaabdddddbdd#eda#a#.....",
"#aaaaaaaaaaaaaaaaaadd#eda##.....",
"#aaaaaaaaaaaaaaaaaaadd#eda#.....",
"#aaaaaaaccacaaaaaaaaadd#eda#....",
"#aaaaaaaaaacaaaaaaaaaad##eda#...",
"#aaaaaacccaaaaaaaaaaaaa#d#eda#..",
"########################dd#eda#.",
"...#dddddddddddddddddddddd##eda#",
"...#aaaaaaaaaaaaaaaaaaaaaa#.####",
"...########################..##."};

static const char *table_xpm[]={
"32 32 5 1",
"# c #585858",
"b c #808080",
". c #c3c3c3",
"a c #dcdcdc",
"c c #ffff00",
"................................",
"................................",
"................................",
"..###a######a######a######bbbb..",
"..###a######a######a######bbbb..",
"..###.######.######.######bbbb..",
".....bbbbbbbbbbbbbbbbbbbbbbaab..",
"..###baaaaaa#aaaaaa#aaaaaabaab..",
"..###baaaaaa#aaaaaa#aaaaaabaab..",
"..###baaaaaa#aaaaaa#aaaaaabaab..",
"..###baaaaaa#aaaaaa#aaaaaabaab..",
"..aaa#####################baab..",
"..###baaaaaa#aaaaaa#ccccccbaab..",
"..###baaaaaa#aaaaaa#ccccccbaab..",
"..###baaaaaa#aaaaaa#ccccccbbbb..",
"..###baaaaaa#aaaaaa#ccccccbbbb..",
"..aaa#####################bbbb..",
"..###baaaaaa#aaaaaa#aaaaaabbbb..",
"..###baaaaaa#aaaaaa#aaaaaabaab..",
"..###baaaaaa#aaaaaa#aaaaaabaab..",
"..###baaaaaa#aaaaaa#aaaaaabaab..",
"..aaa#####################baab..",
"..###baaaaaa#cccccc#aaaaaabaab..",
"..###baaaaaa#cccccc#aaaaaabaab..",
"..###baaaaaa#cccccc#aaaaaabaab..",
"..###baaaaaa#cccccc#aaaaaabaab..",
"..aaa#####################baab..",
"..bbb......bbbbb..........bbbb..",
"..bbb......bbbbb..........bbbb..",
"..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..",
"................................",
"................................"};

/* XPM */
static const char *close_xpm[]={
"32 32 9 1",
"g c #0058c0",
"# c #643a19",
"a c #814a20",
"b c #9c5a27",
"c c #bc6c2f",
". c #c0c0ff",
"e c #dbc908",
"d c #eaa21c",
"f c #ffff00",
"................................",
".........################.......",
"........a##bbbbb#########.......",
"........acd##eeeeeeeeee##.......",
"........acccdaaaeeeeeee##.......",
"........accccccdaaeeeee##.......",
"........accaaacccdaaffe##.......",
"........accaddaaccddafe##.......",
"........accaddddaccdafe##.......",
"........accaddddaccdafe##.......",
"........acccaaddaccdafe##.......",
"........acccccaaaccdafe##.......",
"........accccccccccdafe##.......",
"........accaaacccccdafe##.......",
"........accaddaacccdafe##.......",
"........accaddddaccdafe##.......",
"........accaddddacccafeb#.......",
"........acccaaddacfcafeb#.......",
"........acccccaaacfcafeb#.......",
"........accccccccccdafeb#.......",
"........accaaacccccd#feb#.......",
"........accaddaacccd#fe##.......",
"........accaddddaccd#ee##.......",
"........accaddddaccd#ee##.......",
"........acccaaddaccd#ee##.......",
"........acccccaaaccd#####.......",
"gggggggggaabcccccccd#####ggggggg",
"gggggggggggaaabccccd#ggggggggggg",
"ggggggggggggggaabbdd#ggggggggggg",
"ggggggggggggggggaaaa#ggggggggggg",
"gggggggggggggggggggggggggggggggg",
"gggggggggggggggggggggggggggggggg"};

#endif

